---
- name: reexport nfs
  ansible.builtin.command:
    cmd: exportfs -ra
  changed_when: false

- name: restart smbd
  ansible.builtin.systemd:
    name: smbd
    state: restarted
    enabled: true

- name: restart jupyter
  ansible.builtin.systemd:
    name: jupyter
    state: restarted
    enabled: true
    daemon_reload: true
